---
kind: Template
apiVersion: v1
metadata:
  name: ace-buildconfig-template
objects:
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: ace-only-prebuild
    spec:
      source:
        git:
          uri: https://github.com/ox-prolifics/ace-docker.git
      strategy:
        dockerStrategy:
          dockerfilePath: ubi/Dockerfile.prebuild
          from:
            kind: ImageStreamTag
            name: ubi:latest
      output: 
        to:
          kind: "ImageStreamTag"
          name: "ace-only-prebuild:latest"
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: ace-only
    spec:
      source:
        git:
          uri: https://github.com/ox-prolifics/ace-docker.git
      strategy:
        dockerStrategy:
          dockerfilePath: ubi/Dockerfile.aceonly
          from:
            kind: ImageStreamTag
            name: ace-only-prebuild:latest
      output: 
        to:
          kind: "ImageStreamTag"
          name: "ace-only:latest"
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: ace-mqclient-build
    spec:
      source:
        git:
          uri: https://github.com/ox-prolifics/ace-docker.git
      strategy:
        dockerStrategy:
          dockerfilePath: ubi/Dockerfile.mqclient
          from:
            kind: ImageStreamTag
            name: ace-only:latest
      output:
        to:
          kind: "ImageStreamTag"
          name: "ace-mqclient:latest"
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: ace-bar-build
    spec:
      source:
        git:
          uri: https://github.com/ox-prolifics/ace-docker.git
      strategy:
        dockerStrategy:
          dockerfilePath: ubi/Dockerfile.ace-bar
          from:
            kind: ImageStreamTag
            name: ace-mqclient:latest
      output:
        to:
          kind: "ImageStreamTag"
          name: "ace-service:latest"
parameters:
